name: Mirror GitHub Private Repo to Gitee
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1. 使用 checkout 克隆私有仓库（SSH方式）
      - uses: actions/checkout@v4
        with:
          repository: 1757580896/iptv-api5
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: ./source-repo

      # 2. 设置Git全局配置
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3. 同步到Gitee
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: ./source-repo  # 使用本地路径
          dst: gitee/sunjianw022
          force_update: true
          dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
