name: Mirror Private GitHub Repo to Gitee
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 17 * * *'  # UTC 17:00 (北京时间凌晨1:00)
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1. 配置SSH环境
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      # 2. 验证SSH连接
      - name: Test SSH Connections
        run: |
          ssh -T git@github.com || true
          ssh -T git@gitee.com || true

      # 3. 克隆GitHub私有仓库
      - name: Clone from GitHub
        run: |
          git clone git@github.com:1757580896/iptv-api5.git github-repo
          cd github-repo
          git lfs pull

      # 4. 配置Git身份
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 5. 推送到Gitee
      - name: Push to Gitee
        run: |
          cd github-repo
          git remote add gitee git@gitee.com:sunjianw022/iptv-api5.git || true
          git push gitee main --force
          git push gitee --tags --force
