name: Mirror GitHub Private Repo to Gitee (SSH)
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 17 * * *'  # UTC 17:00 (CST 1:00)
  workflow_dispatch:       # 允许手动触发

jobs:
  mirror:
    name: Sync-GitHub-to-Gitee-via-SSH
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub 私钥

    - name: Mirror to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: git@github.com:1757580896/iptv-api5.git  # 直接使用 SSH URL
        dst: gitee/sunjianw022
        static_list: "iptv-api5"
        force_update: true
        dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}  # Gitee SSH 私钥
       
