name: Mirror Private GitHub Repo to Gitee
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 17 * * *'  # UTC 17:00 (北京时间凌晨1:00)
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1. 配置SSH密钥
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GH_SSH_PRIVATE_KEY }}
            ${{ secrets.GITEE_SSH_PRIVATE_KEY }}

      # 2. 验证SSH连接（调试用）
      - name: Test SSH Connections
        run: |
          ssh -T git@github.com || true
          ssh -T git@gitee.com || true

      # 3. 克隆GitHub私有仓库
      - name: Clone from GitHub
        run: |
          git clone git@github.com:1757580896/iptv-api5.git github-repo
          cd github-repo
          git lfs pull

      # 4. 同步到Gitee
      - name: Push to Gitee
        run: |
          cd github-repo
          git remote add gitee git@gitee.com:sunjianw022/iptv-api5.git
          git push gitee main --force
          git push gitee --tags
